### ISSUE TITLE
Build fails on 32 bit architectures

### ISSUE THREAD

**Issue by davide125** [rbspy/proc-maps#17]
While trying to package proc-maps for Fedora I noticed some build failures on 32 bit architectures:
- armv7hl: https://koji.fedoraproject.org/koji/taskinfo?taskID=78335571
- i686: https://koji.fedoraproject.org/koji/taskinfo?taskID=78335572

You can see the full log by opening build.log on those pages.

**Comment by acj** [comment]
Similar to https://github.com/rbspy/rbspy/issues/341, we haven't tested 32-bit builds in quite a while, and I suspect that usage is minimal. There's no reason that proc-maps couldn't work on 32-bit, at least in principle, but someone would need to step up and maintain support for it. IMO, it's probably best to package 64-bit only.

**Comment by benfred** [comment]
I'm testing out and supporting py-spy on 32-bit arm devices - and py-spy uses this crate as a dependency. I'm pretty sure that this problem is only in the unittests here, and the library itself works fine on 32bit linux devices.  I've added a fix for the unittest in #18 - and tested out that it fixes the problem on a 32bit raspberry pi.

I'm happy to maintain this moving forward,

**Comment by acj** [comment]
@benfred ah, that's great to hear. My mistake. Thanks for the fix!

**Comment by davide125** [comment]
Thanks! I can confirm tests are passing now: https://koji.fedoraproject.org/koji/taskinfo?taskID=78582338
